### ISSUE TITLE
Description and screenshots at addons.mozilla.org (AMO)

### ISSUE THREAD

**Issue by grahamperrin** [ctrlaltdev/socialcall#1]
From https://addons.mozilla.org/addon/social-call/ I have no idea what it looks like, or the situations in which replacements might occur. 

Can you be more descriptive? And include screenshots? 

Help users of AMO to decide whether to install the extension. 

Thanks.

**Comment by ctrlaltdev** [comment]
Before:  
![before](https://user-images.githubusercontent.com/6258960/42719145-1c9946e0-86c6-11e8-9879-54efe3bef04d.png)

After:  
![after](https://user-images.githubusercontent.com/6258960/42719146-1cb7d628-86c6-11e8-8b00-0fb727b6f0cd.png)

I'm going to combine them to make one screenshot and add it to the listing.

I'll try to improve the description too.

**Comment by ctrlaltdev** [comment]
@grahamperrin The listing is updated on AMO, you can close this issue if you think it is sufficient.

**Comment by grahamperrin** [comment]
Yeah, that sums it up :-)
